custom_weather_alerts/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('custom_weather_alerts.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^forecasts/', include('forecasts.urls', namespace='forecasts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

custom_weather_alerts/custom_weather_alerts/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

custom_weather_alerts/forecasts/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserForecasts.as_view(),
        name='list'
    ),
    url(
        regex=r'^~newforecast/$',
        view=views.NewForecast.as_view(),
        name='NewForecast'
    ),
    url(
        regex=r'^delete/(?P<pk>[0-9]+)/$',
        view=views.ForecastDelete.as_view(),
        name='ForecastDelete'
    ),
    url(
        regex=r'^send/(?P<pk>[0-9]+)/$',
        view=views.SendForecastNow.as_view(),
        name='SendForecastNow'
    ),
    url(   # This is not working because I fucked something up
        regex=r'^success/$',
        view=TemplateView.as_view(template_name='success.html'),
        name='success'
    )
]

custom_weather_alerts/custom_weather_alerts/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.http import HttpRequest
from allauth.account.models import EmailAddress



@python_2_unicode_compatible
class User(AbstractUser):

    tz_choices = [('US/Alaska','US/Alaska'),('US/Arizona','US/Arizona'),('US/Central','US/Central'),('US/Eastern','US/Eastern'),('US/Hawaii','US/Hawaii'),('US/Mountain','US/Mountain'),('US/Pacific','US/Pacific')]
    fday_choices = [(1,'1'),(2,'2'),(3,'3'),(4,'4'),(5,'5')]

    # First Name and Last Name do not cover name patterns around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    dtz = models.CharField(_('Default Timezone'), blank=True, max_length=25, choices=tz_choices)
    dday = models.PositiveSmallIntegerField(_('Default Number of Days in Forecast'), choices=fday_choices, default=5)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

custom_weather_alerts/custom_weather_alerts/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, CreateView, DeleteView

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'dtz', 'dday']
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

custom_weather_alerts/custom_weather_alerts/templates/users/forecast_detail.html
{% extends "account/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Forecast" %}{% endblock %}

{% block inner %}
<h1>{% trans 'Forecast Details' %}</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>


{% endblock %}

custom_weather_alerts/custom_weather_alerts/templates/users/new_forecast.html
{% extends "account/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Add a New Forecast" %}{% endblock %}

{% block inner %}
<h1>{% trans 'New Forecast' %}</h1>

{% if user.emailaddress_set.all %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Submit" />
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have a verified e-mail address. You cannot receive Custom Weather Alerts without a verified email address." %}</p>

{% endif %}

{% endblock %}

custom_weather_alerts/custom_weather_alerts/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row m-4">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
      <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

  {% if object == request.user %}
  <!-- Action buttons -->
  <div class="row">
    <div class="col-sm">
      <div class="card">
        <div class="card-header">Account Settings</div>
        <div class="card-body">
          <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info and Settings</a>
          <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card">
        <div class="card-header">Forecasts</div>
        <div class="card-body">
          <a class="btn btn-primary" href="{% url 'forecasts:list' %}" role="button">Active Forecasts</a>
          <a class="btn btn-primary" href="{% url 'forecasts:NewForecast' %}" role="button">New Forecast Profile</a>
        </div>
      </div>
    </div>
  </div>
  <!-- End Action buttons -->


  {% endif %}


</div>
{% endblock content %}

custom_weather_alerts/custom_weather_alerts/templates/users/user_forecasts.html
{% extends "account/base.html" %}

{% load i18n %}

{% block title %}{% trans 'Forecasts' %}{% endblock %}

{% block content %}
<div class="container">

  <div class="row m-4">
    <div class="col-sm"><h2>{% trans 'Your Active Forecasts' %}</h2></div>
    <div class="col-sm"><a class="btn btn-primary" href="{% url 'forecasts:NewForecast' %}" role="button">New Forecast Profile</a></div>
    </div>

  <div class="card-columns">

      {% for ForecastProfile in object_list %}

      <div class="card border-info">
        <div class="card-header">{{ForecastProfile.nickname}}</div>
        <ul class="list-group list-group-inline">
          <li class="list-group-item"><b>Locations:</b> {{ForecastProfile.locations}}</li>
          <li class="list-group-item"><b>Timezone:</b> {{ForecastProfile.timezone}}</li>
          <li class="list-group-item"><b>Timespan:</b>
            {% if ForecastProfile.start_time == 0 %}
            12 am
            {% elif ForecastProfile.start_time < 12 %}
            {{ForecastProfile.start_time}} am
            {% elif ForecastProfile.start_time == 12 %}
            {{ ForecastProfile.start_time }} pm
            {% else %}
            {{ ForecastProfile.start_time|add:"-12" }} pm
            {% endif %}
            -
            {% if ForecastProfile.end_time < 12 %}
            {{ForecastProfile.end_time}} am
            {% elif ForecastProfile.end_time == 12 %}
            {{ ForecastProfile.end_time }} pm
            {% else %}
            {{ ForecastProfile.end_time|add:"-12" }} pm
            {% endif %}
          </li>
          <!-- THIS COULD BE BETTER, BUT IT WILL DO -->
          <li class="list-group-item"><b>Alerts:</b>
            {% if 'A' in ForecastProfile.alerts %}
            All Details,
            {% endif %}
            {% if 'L' in ForecastProfile.alerts %}
            Projected Lows,
            {% endif %}
            {% if 'H' in ForecastProfile.alerts %}
            Projected Highs,
            {% endif %}
            {% if 'F' in ForecastProfile.alerts %}
            Freezing,
            {% endif %}
            {% if 'R' in ForecastProfile.alerts %}
            Rain,
            {% endif %}
            {% if 'S' in ForecastProfile.alerts %}
            Snow
            {% endif %}
          </li>
          <li class="list-group-item"><b>Forecast Length:</b> {{ForecastProfile.days_in_forecast}} days</li>
        </ul>
        <div class="card-footer text-center">
          <form action="{% url 'forecasts:SendForecastNow' ForecastProfile.id %}" method="get">
            <button type="submit" class="btn btn-primary" value="{{ForecastProfile.id}}" name="SendForecast">Send Forecast Now</button>
          </form>
          <form action="{% url 'forecasts:ForecastDelete' ForecastProfile.id %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete Forecast">
          </form>
        </div>
      </div>

      {% endfor %}

  </div>
</div>

{% endblock %}

custom_weather_alerts/custom_weather_alerts/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-success">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

custom_weather_alerts/custom_weather_alerts/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}